name: Deploy Backend to EC2

on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch || github.ref_name }}

      - name: Setup SSH access to EC2
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          if [ -n "${{ secrets.EC2_HOST }}" ]; then
            ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
          else
            echo "EC2_HOST is not set"
            exit 1
          fi

      - name: Deploy backend
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF
            cd /opt/itbem-events-backend
            git pull origin ${{ github.event.inputs.branch || github.ref_name }}
            docker stop itbem-events-backend || true && docker rm itbem-events-backend || true
            docker build -t itbem-events-backend .

            docker run -d --name itbem-events-backend \
              --restart always \
              -p ${{ secrets.BACKEND_PORT }}:${{ secrets.BACKEND_PORT }} \
              -e PORT=${{ secrets.BACKEND_PORT }} \
              -e AWS_REGION='${{ secrets.BACKEND_AWS_REGION }}' \
              -e COGNITO_USER_POOL_ID='${{ secrets.BACKEND_COGNITO_USER_POOL_ID }}' \
              -e COGNITO_CLIENT_ID='${{ secrets.BACKEND_COGNITO_CLIENT_ID }}' \
              -e COGNITO_CLIENT_SECRET='${{ secrets.BACKEND_COGNITO_CLIENT_SECRET }}' \
              -e DB_HOST='${{ secrets.BACKEND_DB_HOST }}' \
              -e DB_USER='${{ secrets.BACKEND_DB_USER }}' \
              -e DB_PASSWORD='${{ secrets.BACKEND_DB_PASSWORD }}' \
              -e DB_NAME='${{ secrets.BACKEND_DB_NAME }}' \
              -e DB_PORT='${{ secrets.BACKEND_DB_PORT }}' \
              -e DB_TIMEZONE='${{ secrets.BACKEND_DB_TIMEZONE }}' \
              -e REDIS_HOST='${{ secrets.BACKEND_REDIS_HOST }}' \
              -e REDIS_PASSWORD='${{ secrets.BACKEND_REDIS_PASSWORD }}' \
              -e REDIS_DB='${{ secrets.BACKEND_REDIS_DB }}' \
              -e GOOGLE_CLIENT_ID='${{ secrets.BACKEND_GOOGLE_CLIENT_ID }}' \
              -e GOOGLE_CLIENT_SECRET='${{ secrets.BACKEND_GOOGLE_CLIENT_SECRET }}' \
              itbem-events-backend
          EOF
